### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xiawei520qq** [teddykoker/unsupervised-deep-homography#14]
thanks for your codes！

After I installed the required package and downloaded the pretrained_coco file, and ran the test file, the following problems occurred：

PS C:\Users\Administrator\Desktop\unsupervised-deep-homography-master> python test.py figures/input_0.gif
Traceback (most recent call last):
  File "test.py", line 51, in <module>
    main(args)
  File "D:\Anaconda\envs\last-homo\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 24, in main
    img_a, patch_a, patch_b, corners, delta = test_set[i]
  File "C:\Users\Administrator\Desktop\unsupervised-deep-homography-master\dataset.py", line 40, in __getitem__
    img_a = Image.open(self.fnames[index])
IndexError: list index out of range

I would like to ask you what went wrong and how to modify it?

**Comment by teddykoker** [comment]
I realize this is years late, but this issue is likely due to the folder you passed not having any images in it.
